Meteor.methods({
  "books.insert":function(book){
    Books.insert(book);
  },
  "books.delete":function(bookid){
    Books.remove(bookid);
  },
  "movies.insert":function(book){
    Movies.insert(book);
  },
  "movies.delete":function(bookid){
    Movies.remove(bookid);
  }
})
